from __future__ import annotations

from typing import Any, Protocol


class ActuatorDriver(Protocol):
    def setup(self, config: dict[str, Any]) -> None: ...
    def get_state(self) -> dict[str, Any]: ...
    def apply(self, command: dict[str, Any]) -> dict[str, Any]: ...
    def health(self) -> dict[str, Any]: ...
